#pragma config(Motor,  port2,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// #pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// functions declarations
void moveStop();
void moveSpeed(int speed);
void m(int motorPort, int speed);
void sm(int motorPort);
void turnRight(int speed);
void turnLeft(int speed);
void motorControl();

// constants
const double RIGHT_TURN_CONSTANT = 0.5;

// main function
task main()
{
	while (1) {
		motorControl();
	}
}

// functions

void motorControl() {
	motor[BL] = vexRT(Ch3);
	motor[FL] = vexRT(Ch3);
	motor[BR] = vexRT(Ch2);
	motor[FR] = vexRT(Ch2);
}

// move in a square shape
void moveSquare(int dist, int speed) {
	for (int i = 0; i < 4; i++) {
		moveSpeed(speed);
		wait(dist / speed);
		if (i < 3) {turnLeft(RIGHT_TURN_CONSTANT * speed);}
	}
	moveStop();
}

//  startMotor alias
void m(int motorPort, int speed) {
	startMotor(motorPort, speed);
}

// stopMotor alias
void sm(int motorPort) {
	stopMotor(motorPort);
}

// move all motors at the same speed
void moveSpeed(int speed) {
	m(FR, speed);
	m(FL, speed);
	m(BR, speed);
	m(BL, speed);
}

// stop all motors
void moveStop() {
	sm(FR);
	sm(FL);
	sm(BR);
	sm(BL);
}

// turn robot right at specified speed
void turnRight(int speed) {
	m(FL, speed);
	m(BL, speed);
	m(FR, -1 * speed);
	m(BR, -1 * speed);
}

// turn robot left at specified speed
void turnLeft(int speed) {
	m(FL, -1 * speed);
	m(BL, -1 * speed);
	m(FR, speed);
	m(BR, speed);
}
