#pragma config(Motor,  port2,           FR,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port4,           BR,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_HBridge, openLoop)
// #pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// functions declarations
void moveStop();
void moveSpeed();
void m();
void sm();

// main function
task main()
{
	moveSpeed(20);
	wait(5);
	moveStop();
}

// functions

void m(int motorPort, int speed) {
	startMotor(motorPort, speed);
}

void sm(int motorPort) {
	stopMotor(motorPort);
}

// move all motors at the same speed
void moveSpeed(int speed) {
  m(FR, speed);
  m(FL, speed);
  m(BR, speed);
 	m(BL, speed);
}

// stop all motors
void moveStop() {
  sm(FR);
  sm(FL);
  sm(BR);
 	sm(BL);
}

void turnRight(int speed) {
	m(FL, speed);
	m(BL, speed);
	m(FR, -1 * speed);
	m(BR, -1 * speed);
}

void turnRight(int speed) {
	m(FL, -1 * speed);
	m(BL, -1 * speed);
	m(FR, speed);
	m(BR, speed);
}
