#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

startMotor(port6, 127);
wait(15);

}
