#pragma config(Motor,  port6,            ,             tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	wait(2);
	setServo(port6, 127);
	wait(2);
	setServo(port6, 0);
  wait(2);
  setServo(port6, -127);

}
